<?php

return
    [
        [
            "name" => "Yachting",
            "image" => "yachting.jpg",
            "Sight seeing" => "",
            "Nature" => "",
            "Wildlife" => "",
            "Watersports" => 10,
            "Exercise / sport" => 1,
            "Relaxation" => "",
            "Food and Drink" => "",
            "Learn" => 1,
            "Volunteer" => "",
            "Challenge" => 1,
            "Events /festivals" => "",
            "Culture" => ""
        ],
        [
            "name" => "Volleyball",
            "image" => "volleyball.jpg",
            "Sight seeing" => "",
            "Nature" => "",
            "Wildlife" => "",
            "Watersports" => "",
            "Exercise / sport" => 1,
            "Relaxation" => "",
            "Food and Drink" => "",
            "Learn" => "",
            "Volunteer" => "",
            "Challenge" => "",
            "Events /festivals" => "",
            "Culture" => ""
        ],
        [
            "name" => "Meditation",
            "image" => "meditation.jpg",
            "Sight seeing" => 1,
            "Nature" => 1,
            "Wildlife" => "",
            "Watersports" => "",
            "Exercise / sport" => "",
            "Relaxation" => 1,
            "Food and Drink" => 1,
            "Learn" => "",
            "Volunteer" => "",
            "Challenge" => "",
            "Events /festivals" => "",
            "Culture" => ""
        ],
        [
            "name" => "Golf",
            "image" => "golf.jpg",
            "Sight seeing" => "",
            "Nature" => "",
            "Wildlife" => "",
            "Watersports" => "",
            "Exercise / sport" => "",
            "Relaxation" => 1,
            "Food and Drink" => "",
            "Learn" => "",
            "Volunteer" => "",
            "Challenge" => "",
            "Events /festivals" => "",
            "Culture" => ""
        ],
        [
            "name" => "Wi-Fi on the beach",
            "image" => "internet.jpg",
            "Sight seeing" => 1,
            "Nature" => 1,
            "Wildlife" => "",
            "Watersports" => "",
            "Exercise / sport" => "",
            "Relaxation" => "",
            "Food and Drink" => "",
            "Learn" => "",
            "Volunteer" => "",
            "Challenge" => "",
            "Events /festivals" => "",
            "Culture" => ""
        ],
        [
            "name" => "Swimming in the forest waterfall",
            "image" => "watrfall.jpg",
            "Sight seeing" => "",
            "Nature" => "",
            "Wildlife" => 1,
            "Watersports" => "",
            "Exercise / sport" => "",
            "Relaxation" => "",
            "Food and Drink" => "",
            "Learn" => "",
            "Volunteer" => "",
            "Challenge" => "",
            "Events /festivals" => "",
            "Culture" => ""
        ],
        [
            "name" => "Swimming with dolphins",
            "image" => "dolphins.jpg",
            "Sight seeing" => "",
            "Nature" => "",
            "Wildlife" => "",
            "Watersports" => "",
            "Exercise / sport" => "",
            "Relaxation" => "",
            "Food and Drink" => "",
            "Learn" => "",
            "Volunteer" => "",
            "Challenge" => "",
            "Events /festivals" => "",
            "Culture" => ""
        ],
        [
            "name" => "Help a puppy in need",
            "image" => "dog.jpg",
            "Sight seeing" => "",
            "Nature" => "",
            "Wildlife" => "",
            "Watersports" => "",
            "Exercise / sport" => 1,
            "Relaxation" => "",
            "Food and Drink" => "",
            "Learn" => "",
            "Volunteer" => 1,
            "Challenge" => "",
            "Events /festivals" => "",
            "Culture" => ""
        ],
        [
            "name" => "Eating exotic fruits",
            "image" => "exotic.jpg",
            "Sight seeing" => "",
            "Nature" => "",
            "Wildlife" => "",
            "Watersports" => "",
            "Exercise / sport" => "",
            "Relaxation" => "",
            "Food and Drink" => "",
            "Learn" => "",
            "Volunteer" => "",
            "Challenge" => "",
            "Events /festivals" => "",
            "Culture" => ""
        ],
        [
            "name" => "Party",
            "image" => "party.jpg",
            "Sight seeing" => "",
            "Nature" => "",
            "Wildlife" => "",
            "Watersports" => "",
            "Exercise / sport" => "",
            "Relaxation" => "",
            "Food and Drink" => "",
            "Learn" => "",
            "Volunteer" => "",
            "Challenge" => "",
            "Events /festivals" => "",
            "Culture" => ""
        ],
        [
            "name" => "The load of the body",
            "image" => "strong.jpg",
            "Sight seeing" => "",
            "Nature" => "",
            "Wildlife" => "",
            "Watersports" => "",
            "Exercise / sport" => "",
            "Relaxation" => "",
            "Food and Drink" => "",
            "Learn" => "",
            "Volunteer" => "",
            "Challenge" => "",
            "Events /festivals" => "",
            "Culture" => ""
        ],
        [
            "name" => "Mythical stories and tales",
            "image" => "monuments.jpg",
            "Sight seeing" => "",
            "Nature" => "",
            "Wildlife" => "",
            "Watersports" => "",
            "Exercise / sport" => "",
            "Relaxation" => "",
            "Food and Drink" => "",
            "Learn" => "",
            "Volunteer" => "",
            "Challenge" => "",
            "Events /festivals" => "",
            "Culture" => ""
        ],
        [
            "name" => "Cycling",
            "image" => "bike.jpg",
            "Sight seeing" => "",
            "Nature" => "",
            "Wildlife" => "",
            "Watersports" => "",
            "Exercise / sport" => "",
            "Relaxation" => "",
            "Food and Drink" => "",
            "Learn" => "",
            "Volunteer" => "",
            "Challenge" => "",
            "Events /festivals" => "",
            "Culture" => ""
        ],
        [
            "name" => "Running on the beach",
            "image" => "running.jpg",
            "Sight seeing" => "",
            "Nature" => "",
            "Wildlife" => "",
            "Watersports" => "",
            "Exercise / sport" => "",
            "Relaxation" => "",
            "Food and Drink" => "",
            "Learn" => "",
            "Volunteer" => "",
            "Challenge" => "",
            "Events /festivals" => "",
            "Culture" => ""
        ],
        [
            "name" => "Feeding the elephant",
            "image" => "elephants.jpg",
            "Sight seeing" => "",
            "Nature" => "",
            "Wildlife" => "",
            "Watersports" => "",
            "Exercise / sport" => "",
            "Relaxation" => "",
            "Food and Drink" => "",
            "Learn" => "",
            "Volunteer" => "",
            "Challenge" => "",
            "Events /festivals" => "",
            "Culture" => ""
        ],
        [
            "name" => "Amusement park",
            "image" => "amusement.jpg",
            "Sight seeing" => "",
            "Nature" => "",
            "Wildlife" => "",
            "Watersports" => "",
            "Exercise / sport" => "",
            "Relaxation" => "",
            "Food and Drink" => "",
            "Learn" => "",
            "Volunteer" => "",
            "Challenge" => "",
            "Events /festivals" => "",
            "Culture" => ""
        ]
    ];