<?php

return [
    [
        "Experience"=> "Thai Boxing Training Camp",
        "Region"=> "Asia",
        "Country"=> "Thailand",
        "City"=> "Various",
        "When (month)"=> [0],
        "minDuration"=> 1,
        "maxDuration"=> 7,
        "Sight seeing"=> 1,
        "Nature"=> 1,
        "Wildlife"=> 1,
        "Watersports"=> 1,
        "Exercise / sport"=> 10,
        "Relaxation"=> 1,
        "Food and Drink"=> 1,
        "Learn"=> 10,
        "Volunteer"=> 1,
        "Challenge"=> 10,
        "Events /festivals"=> 1,
        "Culture"=> 5
    ],
    [
        "Experience"=> "Rock Climbing",
        "Region"=> "Asia",
        "Country"=> "Thailand",
        "City"=> "Krabi",
        "When (month)"=> [11,12,1,2,3,4],
        "minDuration"=> "1",
        "maxDuration"=> "",
        "Sight seeing"=> 5,
        "Nature"=> 10,
        "Wildlife"=> 5,
        "Watersports"=> 1,
        "Exercise / sport"=> 10,
        "Relaxation"=> 1,
        "Food and Drink"=> 1,
        "Learn"=> 5,
        "Volunteer"=> 1,
        "Challenge"=> 10,
        "Events /festivals"=> 1,
        "Culture"=> 1
    ],
    [
        "Experience"=> "Kayaking",
        "Region"=> "Asia",
        "Country"=> "Thailand",
        "City"=> "Krabi",
        "When (month)"=> [
            0
        ],
        "minDuration"=> 1,
        "maxDuration"=> 1,
        "Sight seeing"=> 5,
        "Nature"=> 10,
        "Wildlife"=> 5,
        "Watersports"=> 10,
        "Exercise / sport"=> 10,
        "Relaxation"=> 1,
        "Food and Drink"=> 1,
        "Learn"=> 5,
        "Volunteer"=> 1,
        "Challenge"=> 5,
        "Events /festivals"=> 1,
        "Culture"=> 1
    ],
    [
        "Experience"=> "WW Rafting",
        "Region"=> "Asia",
        "Country"=> "Thailand",
        "City"=> "Krabi, Phuket, Chiang Mai",
        "When (month)"=> [7,8,9,10,11,12,1],
        "minDuration"=> 1,
        "maxDuration"=> 1,
        "Sight seeing"=> 5,
        "Nature"=> 10,
        "Wildlife"=> 5,
        "Watersports"=> 10,
        "Exercise / sport"=> 10,
        "Relaxation"=> 1,
        "Food and Drink"=> 1,
        "Learn"=> 5,
        "Volunteer"=> 1,
        "Challenge"=> 5,
        "Events /festivals"=> 1,
        "Culture"=> 1
    ],
    [
        "Experience"=> "Scuba Diving",
        "Region"=> "Asia",
        "Country"=> "Thailand",
        "City"=> "Various",
        "When (month)"=> [
            0
        ],
        "minDuration"=> 1,
        "maxDuration"=> 4,
        "Sight seeing"=> 5,
        "Nature"=> 5,
        "Wildlife"=> 10,
        "Watersports"=> 10,
        "Exercise / sport"=> 5,
        "Relaxation"=> 1,
        "Food and Drink"=> 1,
        "Learn"=> 10,
        "Volunteer"=> 1,
        "Challenge"=> 5,
        "Events /festivals"=> 1,
        "Culture"=> 1
    ],
    [
        "Experience"=> "Snorkelling tours",
        "Region"=> "Asia",
        "Country"=> "Thailand",
        "City"=> "Various",
        "When (month)"=> [
            0
        ],
        "minDuration"=> 1,
        "maxDuration"=> 1,
        "Sight seeing"=> 5,
        "Nature"=> 5,
        "Wildlife"=> 10,
        "Watersports"=> 10,
        "Exercise / sport"=> 5,
        "Relaxation"=> 1,
        "Food and Drink"=> 1,
        "Learn"=> 1,
        "Volunteer"=> 1,
        "Challenge"=> 5,
        "Events /festivals"=> 1,
        "Culture"=> 1
    ],
    [
        "Experience"=> "Stand up Paddle Boarding",
        "Region"=> "Asia",
        "Country"=> "Thailand",
        "City"=> "Various",
        "When (month)"=> [
            0
        ],
        "minDuration"=> 1,
        "maxDuration"=> 1,
        "Sight seeing"=> 5,
        "Nature"=> 5,
        "Wildlife"=> 5,
        "Watersports"=> 10,
        "Exercise / sport"=> 10,
        "Relaxation"=> 1,
        "Food and Drink"=> 1,
        "Learn"=> 1,
        "Volunteer"=> 1,
        "Challenge"=> 5,
        "Events /festivals"=> 1,
        "Culture"=> 1
    ],
    [
        "Experience"=> "Jungle Trek",
        "Region"=> "Asia",
        "Country"=> "Thailand",
        "City"=> "Chiang Mai",
        "When (month)"=> [
            0
        ],
        "minDuration"=> 1,
        "maxDuration"=> "",
        "Sight seeing"=> 10,
        "Nature"=> 10,
        "Wildlife"=> 10,
        "Watersports"=> 1,
        "Exercise / sport"=> 5,
        "Relaxation"=> 1,
        "Food and Drink"=> 1,
        "Learn"=> 1,
        "Volunteer"=> 1,
        "Challenge"=> 5,
        "Events /festivals"=> 1,
        "Culture"=> 5
    ],
    [
        "Experience"=> "Canyoning and Abseiling",
        "Region"=> "Asia",
        "Country"=> "Thailand",
        "City"=> "Chiang Mai",
        "When (month)"=> [
            0
        ],
        "minDuration"=> 1,
        "maxDuration"=> 1,
        "Sight seeing"=> 5,
        "Nature"=> 10,
        "Wildlife"=> 5,
        "Watersports"=> 5,
        "Exercise / sport"=> 10,
        "Relaxation"=> 1,
        "Food and Drink"=> 1,
        "Learn"=> 10,
        "Volunteer"=> 1,
        "Challenge"=> 10,
        "Events /festivals"=> 1,
        "Culture"=> 1
    ],
    [
        "Experience"=> "Zip Wire Experience",
        "Region"=> "Asia",
        "Country"=> "Thailand",
        "City"=> "Chiang Mai",
        "When (month)"=> [
            0
        ],
        "minDuration"=> 1,
        "maxDuration"=> 1,
        "Sight seeing"=> 5,
        "Nature"=> 10,
        "Wildlife"=> 5,
        "Watersports"=> 1,
        "Exercise / sport"=> 10,
        "Relaxation"=> 1,
        "Food and Drink"=> 1,
        "Learn"=> 1,
        "Volunteer"=> 1,
        "Challenge"=> 5,
        "Events /festivals"=> 1,
        "Culture"=> 1
    ],
    [
        "Experience"=> "Visit an Elephant Sanctuary (Thailand)",
        "Region"=> "Asia",
        "Country"=> "Thailand",
        "City"=> "Various",
        "When (month)"=> [
            0
        ],
        "minDuration"=> 1,
        "maxDuration"=> "",
        "Sight seeing"=> 5,
        "Nature"=> 5,
        "Wildlife"=> 10,
        "Watersports"=> 1,
        "Exercise / sport"=> 1,
        "Relaxation"=> 5,
        "Food and Drink"=> 1,
        "Learn"=> 5,
        "Volunteer"=> 1,
        "Challenge"=> 1,
        "Events /festivals"=> 1,
        "Culture"=> 5
    ],
    [
        "Experience"=> "Volunteer at an Elephant Sanctuary (Thailand)",
        "Region"=> "Asia",
        "Country"=> "Thailand",
        "City"=> "Various",
        "When (month)"=> [
            0
        ],
        "minDuration"=> 1,
        "maxDuration"=> "",
        "Sight seeing"=> 5,
        "Nature"=> 5,
        "Wildlife"=> 10,
        "Watersports"=> 1,
        "Exercise / sport"=> 1,
        "Relaxation"=> 1,
        "Food and Drink"=> 1,
        "Learn"=> 5,
        "Volunteer"=> 10,
        "Challenge"=> 5,
        "Events /festivals"=> 1,
        "Culture"=> 5
    ],
    [
        "Experience"=> "Volunteer at a Wildlife Rescue Centre",
        "Region"=> "Asia",
        "Country"=> "Thailand",
        "City"=> "Various",
        "When (month)"=> [
            0
        ],
        "minDuration"=> 7,
        "maxDuration"=> "",
        "Sight seeing"=> 5,
        "Nature"=> 5,
        "Wildlife"=> 10,
        "Watersports"=> 1,
        "Exercise / sport"=> 1,
        "Relaxation"=> 1,
        "Food and Drink"=> 1,
        "Learn"=> 5,
        "Volunteer"=> 10,
        "Challenge"=> 5,
        "Events /festivals"=> 1,
        "Culture"=> 5
    ],
    [
        "Experience"=> "Sea and Beach Clean Up (Thailand)",
        "Region"=> "Asia",
        "Country"=> "Thailand",
        "City"=> "Various",
        "When (month)"=> [
            0
        ],
        "minDuration"=> 7,
        "maxDuration"=> "",
        "Sight seeing"=> 5,
        "Nature"=> 5,
        "Wildlife"=> 10,
        "Watersports"=> 10,
        "Exercise / sport"=> 5,
        "Relaxation"=> 1,
        "Food and Drink"=> 1,
        "Learn"=> 5,
        "Volunteer"=> 10,
        "Challenge"=> 5,
        "Events /festivals"=> 1,
        "Culture"=> 5
    ],
    [
        "Experience"=> "Explore Khao Sok National Park",
        "Region"=> "Asia",
        "Country"=> "Thailand",
        "City"=> "Khao Sok",
        "When (month)"=> [
            0
        ],
        "minDuration"=> 1,
        "maxDuration"=> "",
        "Sight seeing"=> 10,
        "Nature"=> 10,
        "Wildlife"=> 10,
        "Watersports"=> 5,
        "Exercise / sport"=> 5,
        "Relaxation"=> 1,
        "Food and Drink"=> 1,
        "Learn"=> 5,
        "Volunteer"=> 1,
        "Challenge"=> 1,
        "Events /festivals"=> 1,
        "Culture"=> 5
    ],
    [
        "Experience"=> "Thai Cooking Class",
        "Region"=> "Asia",
        "Country"=> "Thailand",
        "City"=> "Various",
        "When (month)"=> [
            0
        ],
        "minDuration"=> 1,
        "maxDuration"=> "",
        "Sight seeing"=> 1,
        "Nature"=> 1,
        "Wildlife"=> 1,
        "Watersports"=> 1,
        "Exercise / sport"=> 1,
        "Relaxation"=> 5,
        "Food and Drink"=> 10,
        "Learn"=> 10,
        "Volunteer"=> 1,
        "Challenge"=> 1,
        "Events /festivals"=> 1,
        "Culture"=> 10
    ],
    [
        "Experience"=> "Thai Street Food Feast",
        "Region"=> "Asia",
        "Country"=> "Thailand",
        "City"=> "Bangkok, Chiang Mai",
        "When (month)"=> [
            0
        ],
        "minDuration"=> 1,
        "maxDuration"=> 1,
        "Sight seeing"=> 5,
        "Nature"=> 1,
        "Wildlife"=> 1,
        "Watersports"=> 1,
        "Exercise / sport"=> 1,
        "Relaxation"=> 5,
        "Food and Drink"=> 10,
        "Learn"=> 5,
        "Volunteer"=> 1,
        "Challenge"=> 1,
        "Events /festivals"=> 1,
        "Culture"=> 10
    ],
    [
        "Experience"=> "Floating Market Tour",
        "Region"=> "Asia",
        "Country"=> "Thailand",
        "City"=> "Bangkok",
        "When (month)"=> [
            0
        ],
        "minDuration"=> 1,
        "maxDuration"=> 1,
        "Sight seeing"=> 10,
        "Nature"=> 1,
        "Wildlife"=> 1,
        "Watersports"=> 1,
        "Exercise / sport"=> 1,
        "Relaxation"=> 5,
        "Food and Drink"=> 10,
        "Learn"=> 1,
        "Volunteer"=> 1,
        "Challenge"=> 1,
        "Events /festivals"=> 1,
        "Culture"=> 10
    ],
    [
        "Experience"=> "Bangkok City and Temple Tour",
        "Region"=> "Asia",
        "Country"=> "Thailand",
        "City"=> "Various",
        "When (month)"=> [
            0
        ],
        "minDuration"=> 1,
        "maxDuration"=> 1,
        "Sight seeing"=> 10,
        "Nature"=> 1,
        "Wildlife"=> 1,
        "Watersports"=> 1,
        "Exercise / sport"=> 1,
        "Relaxation"=> 5,
        "Food and Drink"=> 1,
        "Learn"=> 5,
        "Volunteer"=> 1,
        "Challenge"=> 1,
        "Events /festivals"=> 1,
        "Culture"=> 10
    ],
    [
        "Experience"=> "Ayutthaya Temples and River Cruise",
        "Region"=> "Asia",
        "Country"=> "Thailand",
        "City"=> "Bangkok",
        "When (month)"=> [
            0
        ],
        "minDuration"=> 1,
        "maxDuration"=> 1,
        "Sight seeing"=> 10,
        "Nature"=> 1,
        "Wildlife"=> 1,
        "Watersports"=> 1,
        "Exercise / sport"=> 1,
        "Relaxation"=> 5,
        "Food and Drink"=> 1,
        "Learn"=> 5,
        "Volunteer"=> 1,
        "Challenge"=> 1,
        "Events /festivals"=> 1,
        "Culture"=> 10
    ],
    [
        "Experience"=> "Ayutthaya Cycle Tour",
        "Region"=> "Asia",
        "Country"=> "Thailand",
        "City"=> "Bangkok",
        "When (month)"=> [
            0
        ],
        "minDuration"=> 1,
        "maxDuration"=> 1,
        "Sight seeing"=> 10,
        "Nature"=> 1,
        "Wildlife"=> 1,
        "Watersports"=> 1,
        "Exercise / sport"=> 5,
        "Relaxation"=> 5,
        "Food and Drink"=> 1,
        "Learn"=> 5,
        "Volunteer"=> 1,
        "Challenge"=> 1,
        "Events /festivals"=> 1,
        "Culture"=> 10
    ],
    [
        "Experience"=> "Meditation and Mindfulness",
        "Region"=> "Asia",
        "Country"=> "Thailand",
        "City"=> "Various",
        "When (month)"=> [
            0
        ],
        "minDuration"=> 1,
        "maxDuration"=> "",
        "Sight seeing"=> 1,
        "Nature"=> 5,
        "Wildlife"=> 1,
        "Watersports"=> 1,
        "Exercise / sport"=> 1,
        "Relaxation"=> 10,
        "Food and Drink"=> 1,
        "Learn"=> 10,
        "Volunteer"=> 1,
        "Challenge"=> 1,
        "Events /festivals"=> 1,
        "Culture"=> 10
    ],
    [
        "Experience"=> "Yoga",
        "Region"=> "Asia",
        "Country"=> "Thailand",
        "City"=> "Various",
        "When (month)"=> [
            0
        ],
        "minDuration"=> 1,
        "maxDuration"=> "",
        "Sight seeing"=> 1,
        "Nature"=> 5,
        "Wildlife"=> 1,
        "Watersports"=> 1,
        "Exercise / sport"=> 10,
        "Relaxation"=> 10,
        "Food and Drink"=> 1,
        "Learn"=> 10,
        "Volunteer"=> 1,
        "Challenge"=> 1,
        "Events /festivals"=> 1,
        "Culture"=> 10
    ],
    [
        "Experience"=> "Fitness Boot Camp Thailand",
        "Region"=> "Asia",
        "Country"=> "Thailand",
        "City"=> "Chiang Mai",
        "When (month)"=> [
            0
        ],
        "minDuration"=> 7,
        "maxDuration"=> 28,
        "Sight seeing"=> 5,
        "Nature"=> 5,
        "Wildlife"=> 5,
        "Watersports"=> 1,
        "Exercise / sport"=> 10,
        "Relaxation"=> 1,
        "Food and Drink"=> 1,
        "Learn"=> 5,
        "Volunteer"=> 1,
        "Challenge"=> 10,
        "Events /festivals"=> 1,
        "Culture"=> 5
    ],
    [
        "Experience"=> "Authentic Thai Massage",
        "Region"=> "Asia",
        "Country"=> "Thailand",
        "City"=> "Various",
        "When (month)"=> [
            0
        ],
        "minDuration"=> 1,
        "maxDuration"=> 1,
        "Sight seeing"=> 1,
        "Nature"=> 1,
        "Wildlife"=> 1,
        "Watersports"=> 1,
        "Exercise / sport"=> 1,
        "Relaxation"=> 10,
        "Food and Drink"=> 1,
        "Learn"=> 1,
        "Volunteer"=> 1,
        "Challenge"=> 1,
        "Events /festivals"=> 1,
        "Culture"=> 5
    ],
    [
        "Experience"=> "Learn Thai Massage",
        "Region"=> "Asia",
        "Country"=> "Thailand",
        "City"=> "Various",
        "When (month)"=> [
            0
        ],
        "minDuration"=> 1,
        "maxDuration"=> "",
        "Sight seeing"=> 1,
        "Nature"=> 1,
        "Wildlife"=> 1,
        "Watersports"=> 1,
        "Exercise / sport"=> 1,
        "Relaxation"=> 10,
        "Food and Drink"=> 1,
        "Learn"=> 10,
        "Volunteer"=> 1,
        "Challenge"=> 1,
        "Events /festivals"=> 1,
        "Culture"=> 5
    ],
    [
        "Experience"=> "Hill Tribe Tour and Homestay",
        "Region"=> "Asia",
        "Country"=> "Thailand",
        "City"=> "Chiang Mai",
        "When (month)"=> [0],
        "minDuration"=> 1,
        "maxDuration"=> 9,
        "Sight seeing"=> 10,
        "Nature"=> 10,
        "Wildlife"=> 5,
        "Watersports"=> 1,
        "Exercise / sport"=> 1,
        "Relaxation"=> 5,
        "Food and Drink"=> 5,
        "Learn"=> 10,
        "Volunteer"=> 1,
        "Challenge"=> 1,
        "Events /festivals"=> 1,
        "Culture"=> 10
    ],
    [
        "Experience"=> "Wet and Wild Songkran",
        "Region"=> "Asia",
        "Country"=> "Thailand",
        "City"=> "Chiang Mai",
        "When (month)"=> [4],
        "minDuration"=> 1,
        "maxDuration"=> 3,
        "Sight seeing"=> 5,
        "Nature"=> 1,
        "Wildlife"=> 1,
        "Watersports"=> 5,
        "Exercise / sport"=> 1,
        "Relaxation"=> 1,
        "Food and Drink"=> 1,
        "Learn"=> 1,
        "Volunteer"=> 1,
        "Challenge"=> 1,
        "Events /festivals"=> 10,
        "Culture"=> 5
    ],
    [
        "Experience"=> "Full Moon Party Experience",
        "Region"=> "Asia",
        "Country"=> "Thailand",
        "City"=> "Koh Phangan",
        "When (month)"=> [
            0
        ],
        "minDuration"=> 1,
        "maxDuration"=> 2,
        "Sight seeing"=> 5,
        "Nature"=> 5,
        "Wildlife"=> 1,
        "Watersports"=> 1,
        "Exercise / sport"=> 1,
        "Relaxation"=> 1,
        "Food and Drink"=> 1,
        "Learn"=> 1,
        "Volunteer"=> 1,
        "Challenge"=> 1,
        "Events /festivals"=> 10,
        "Culture"=> 5
    ],
    [
        "Experience"=> "Light up the Sky at Loi Krathong",
        "Region"=> "Asia",
        "Country"=> "Thailand",
        "City"=> "Chiang Mai",
        "When (month)"=> [11],
        "minDuration"=> 1,
        "maxDuration"=> 1,
        "Sight seeing"=> 10,
        "Nature"=> 1,
        "Wildlife"=> 1,
        "Watersports"=> 1,
        "Exercise / sport"=> 1,
        "Relaxation"=> 5,
        "Food and Drink"=> 1,
        "Learn"=> 5,
        "Volunteer"=> 1,
        "Challenge"=> 1,
        "Events /festivals"=> 10,
        "Culture"=> 10
    ],
    [
        "Experience"=> "Island Hopping - Gulf of Thailand",
        "Region"=> "Asia",
        "Country"=> "Thailand",
        "City"=> "East",
        "When (month)"=> [2,3,4,5,6,7,8,9],
        "minDuration"=> 3,
        "maxDuration"=> "",
        "Sight seeing"=> 10,
        "Nature"=> 10,
        "Wildlife"=> 1,
        "Watersports"=> 1,
        "Exercise / sport"=> 1,
        "Relaxation"=> 10,
        "Food and Drink"=> 1,
        "Learn"=> 1,
        "Volunteer"=> 1,
        "Challenge"=> 1,
        "Events /festivals"=> 1,
        "Culture"=> 5
    ],
    [
        "Experience"=> "Island Hopping - Andaman Sea",
        "Region"=> "Asia",
        "Country"=> "Thailand",
        "City"=> "West",
        "When (month)"=> [11,12,1,2,3,4],
        "minDuration"=> 3,
        "maxDuration"=> 3,
        "Sight seeing"=> 10,
        "Nature"=> 10,
        "Wildlife"=> 1,
        "Watersports"=> 1,
        "Exercise / sport"=> 1,
        "Relaxation"=> 10,
        "Food and Drink"=> 1,
        "Learn"=> 1,
        "Volunteer"=> 1,
        "Challenge"=> 1,
        "Events /festivals"=> 1,
        "Culture"=> 5
    ],
    [
        "Experience"=> "Intro to Surfing",
        "Region"=> "Asia",
        "Country"=> "Sri Lanka",
        "City"=> "South-West",
        "When (month)"=> [10,11,12,1,2,3,4],
        "minDuration"=> 1,
        "maxDuration"=> 1,
        "Sight seeing"=> 5,
        "Nature"=> 5,
        "Wildlife"=> 1,
        "Watersports"=> 10,
        "Exercise / sport"=> 10,
        "Relaxation"=> 5,
        "Food and Drink"=> 1,
        "Learn"=> 10,
        "Volunteer"=> 1,
        "Challenge"=> 10,
        "Events /festivals"=> 1,
        "Culture"=> 1
    ],
    [
        "Experience"=> "Master Surfing in Sri Lanka",
        "Region"=> "Asia",
        "Country"=> "Sri Lanka",
        "City"=> "South-West",
        "When (month)"=> [10,11,12,1,2,3,4],
        "minDuration"=> 5,
        "maxDuration"=> "",
        "Sight seeing"=> 5,
        "Nature"=> 5,
        "Wildlife"=> 1,
        "Watersports"=> 10,
        "Exercise / sport"=> 10,
        "Relaxation"=> 5,
        "Food and Drink"=> 1,
        "Learn"=> 10,
        "Volunteer"=> 1,
        "Challenge"=> 10,
        "Events /festivals"=> 1,
        "Culture"=> 1
    ],
    [
        "Experience"=> "Surf and Yoga Retreat",
        "Region"=> "Asia",
        "Country"=> "Sri Lanka",
        "City"=> "South-West",
        "When (month)"=> [10,11,12,1,2,3,4],
        "minDuration"=> 7,
        "maxDuration"=> "",
        "Sight seeing"=> 5,
        "Nature"=> 5,
        "Wildlife"=> 1,
        "Watersports"=> 10,
        "Exercise / sport"=> 10,
        "Relaxation"=> 10,
        "Food and Drink"=> 1,
        "Learn"=> 10,
        "Volunteer"=> 1,
        "Challenge"=> 10,
        "Events /festivals"=> 1,
        "Culture"=> 1
    ],
    [
        "Experience"=> "Intro to Windsurfing",
        "Region"=> "Asia",
        "Country"=> "Sri Lanka",
        "City"=> "Kalpitiya",
        "When (month)"=> [5,6,7,8,9,12,1,2],
        "minDuration"=> 2,
        "maxDuration"=> 3,
        "Sight seeing"=> 5,
        "Nature"=> 5,
        "Wildlife"=> 1,
        "Watersports"=> 10,
        "Exercise / sport"=> 10,
        "Relaxation"=> 1,
        "Food and Drink"=> 1,
        "Learn"=> 10,
        "Volunteer"=> 1,
        "Challenge"=> 10,
        "Events /festivals"=> 1,
        "Culture"=> 1
    ],
    [
        "Experience"=> "Learn to Kitesurf",
        "Region"=> "Asia",
        "Country"=> "Sri Lanka",
        "City"=> "Kalpitiya",
        "When (month)"=> [5,6,7,8,9,12,1,2],
        "minDuration"=> 1,
        "maxDuration"=> 4,
        "Sight seeing"=> 5,
        "Nature"=> 5,
        "Wildlife"=> 1,
        "Watersports"=> 10,
        "Exercise / sport"=> 10,
        "Relaxation"=> 1,
        "Food and Drink"=> 1,
        "Learn"=> 10,
        "Volunteer"=> 1,
        "Challenge"=> 10,
        "Events /festivals"=> 1,
        "Culture"=> 1
    ],
    [
        "Experience"=> "Intro to Yoga",
        "Region"=> "Asia",
        "Country"=> "Sri Lanka",
        "City"=> "South-West",
        "When (month)"=> [10,11,12,1,2,3,4],
        "minDuration"=> 1,
        "maxDuration"=> "",
        "Sight seeing"=> 1,
        "Nature"=> 5,
        "Wildlife"=> 1,
        "Watersports"=> 1,
        "Exercise / sport"=> 10,
        "Relaxation"=> 10,
        "Food and Drink"=> 5,
        "Learn"=> 10,
        "Volunteer"=> 1,
        "Challenge"=> 1,
        "Events /festivals"=> 1,
        "Culture"=> 5
    ],
    [
        "Experience"=> "Ayurvedic Wellness Retreat",
        "Region"=> "Asia",
        "Country"=> "Sri Lanka",
        "City"=> "South-West",
        "When (month)"=> [10,11,12,1,2,3,4],
        "minDuration"=> 7,
        "maxDuration"=> 7,
        "Sight seeing"=> 1,
        "Nature"=> 5,
        "Wildlife"=> 1,
        "Watersports"=> 1,
        "Exercise / sport"=> 5,
        "Relaxation"=> 10,
        "Food and Drink"=> 5,
        "Learn"=> 10,
        "Volunteer"=> 1,
        "Challenge"=> 1,
        "Events /festivals"=> 1,
        "Culture"=> 10
    ],
    [
        "Experience"=> "Yala National Park Safari",
        "Region"=> "Asia",
        "Country"=> "Sri Lanka",
        "City"=> "South-East",
        "When (month)"=> [1,2,3,4,5,6,7,8,11,12],
        "minDuration"=> 1,
        "maxDuration"=> 2,
        "Sight seeing"=> 10,
        "Nature"=> 10,
        "Wildlife"=> 10,
        "Watersports"=> 1,
        "Exercise / sport"=> 1,
        "Relaxation"=> 1,
        "Food and Drink"=> 1,
        "Learn"=> 1,
        "Volunteer"=> 1,
        "Challenge"=> 1,
        "Events /festivals"=> 1,
        "Culture"=> 5
    ],
    [
        "Experience"=> "Udawalawe National Park Safari",
        "Region"=> "Asia",
        "Country"=> "Sri Lanka",
        "City"=> "Inland",
        "When (month)"=> [
            0
        ],
        "minDuration"=> 1,
        "maxDuration"=> "",
        "Sight seeing"=> 10,
        "Nature"=> 10,
        "Wildlife"=> 10,
        "Watersports"=> 1,
        "Exercise / sport"=> 1,
        "Relaxation"=> 1,
        "Food and Drink"=> 1,
        "Learn"=> 1,
        "Volunteer"=> 1,
        "Challenge"=> 1,
        "Events /festivals"=> 1,
        "Culture"=> 5
    ],
    [
        "Experience"=> "Elephants at Minneriya National Park",
        "Region"=> "Asia",
        "Country"=> "Sri Lanka",
        "City"=> "Habarana",
        "When (month)"=> [7,8,9,10],
        "minDuration"=> 1,
        "maxDuration"=> 1,
        "Sight seeing"=> 10,
        "Nature"=> 10,
        "Wildlife"=> 10,
        "Watersports"=> 1,
        "Exercise / sport"=> 1,
        "Relaxation"=> 1,
        "Food and Drink"=> 1,
        "Learn"=> 1,
        "Volunteer"=> 1,
        "Challenge"=> 1,
        "Events /festivals"=> 1,
        "Culture"=> 5
    ],
    [
        "Experience"=> "Visit an Elephant Sanctuary (Sri Lanka)",
        "Region"=> "Asia",
        "Country"=> "Sri Lanka",
        "City"=> "Kegalle",
        "When (month)"=> [
            0
        ],
        "minDuration"=> 1,
        "maxDuration"=> 1,
        "Sight seeing"=> 5,
        "Nature"=> 10,
        "Wildlife"=> 10,
        "Watersports"=> 1,
        "Exercise / sport"=> 1,
        "Relaxation"=> 1,
        "Food and Drink"=> 1,
        "Learn"=> 1,
        "Volunteer"=> 5,
        "Challenge"=> 1,
        "Events /festivals"=> 1,
        "Culture"=> 5
    ],
    [
        "Experience"=> "Volunteer at an Elephant Sanctuary (Sri Lanka)",
        "Region"=> "Asia",
        "Country"=> "Sri Lanka",
        "City"=> "Kegalle",
        "When (month)"=> [
            0
        ],
        "minDuration"=> 7,
        "maxDuration"=> 21,
        "Sight seeing"=> 5,
        "Nature"=> 10,
        "Wildlife"=> 10,
        "Watersports"=> 1,
        "Exercise / sport"=> 1,
        "Relaxation"=> 1,
        "Food and Drink"=> 1,
        "Learn"=> 1,
        "Volunteer"=> 10,
        "Challenge"=> 10,
        "Events /festivals"=> 1,
        "Culture"=> 10
    ],
    [
        "Experience"=> "The World's Most Scenic Train Journey",
        "Region"=> "Asia",
        "Country"=> "Sri Lanka",
        "City"=> "Haputale to Ella",
        "When (month)"=> [
            0
        ],
        "minDuration"=> 1,
        "maxDuration"=> 2,
        "Sight seeing"=> 10,
        "Nature"=> 5,
        "Wildlife"=> 1,
        "Watersports"=> 1,
        "Exercise / sport"=> 1,
        "Relaxation"=> 1,
        "Food and Drink"=> 1,
        "Learn"=> 1,
        "Volunteer"=> 1,
        "Challenge"=> 1,
        "Events /festivals"=> 1,
        "Culture"=> 10
    ]
];